### ISSUE TITLE
The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform

### ISSUE THREAD

**Issue by PnYMaT** [flathub/app.rednotebook.RedNotebook#23]
Hi,

When check update for app.rednotebook.RedNotebook on flatpak, i have this warning :
"Looking for updates…
Info: org.gnome.Platform//42 is end-of-life, with reason:
The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
app.rednotebook.RedNotebook
Nothing to do."

To Reproduce just run this command on Debian like system :
$ flatpak update app.rednotebook.RedNotebook

To solve this, it seems just use more recent runtime for gnome, such as gnome 43 runtime

Many thanks :)

**Comment by jendrikseipp** [comment]
Thanks for the report! This is fixed in #24.
