### ISSUE TITLE
Rednotebook 2.20 fails to start

### ISSUE THREAD

**Issue by takluyver** [flathub/app.rednotebook.RedNotebook#5]
I updated to 2.20 recently, but now Rednotebook fails to start. Running `flatpak run app.rednotebook.RedNotebook` I see different error messages; seemingly at random, including `double free or corruption (out)` or `(rednotebook:2): Gtk-CRITICAL **: 14:58:35.361: _gtk_settings_get_style_cascade: assertion 'GTK_IS_SETTINGS (settings)' failed`, and `(rednotebook:2): Gtk-CRITICAL **: 15:00:52.944: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed`.

Some of the normal logging messages appear as well, in varying amounts. With the 'double free' error, I see just 3 lines (log file, system encoding, language). With others, there's more info - here's a log file accompanying the 'GTK_IS_WIDGET' error: 
[rednotebook.log](https://github.com/flathub/app.rednotebook.RedNotebook/files/5016413/rednotebook.log).

It's not Python crashing before any RN code runs (or the log messages wouldn't appear). Several other Flatpak apps still start OK.

**Comment by takluyver** [comment]
I also tried moving my `~/.rednotebook` directory to give it a blank slate, but that didn't solve it.

**Comment by takluyver** [comment]
I think I've traced this down to the `enchant` spellchecking library.

**Comment by jendrikseipp** [comment]
Thanks for your investigation and the fix!

**Comment by takluyver** [comment]
Thanks :-)
